- name: Setup reverse proxy
  hosts: aws
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: Update
      ansible.builtin.yum:
        update_cache: true
    - name: Install
      ansible.builtin.yum:
        name: nginx

- name: Setup tunneling via ssh
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tasks:
    - name: Copy key file
      ansible.builtin.copy:
        src: ./files/ec2.pem
        dest: ./.ssh/ec2.pem
        mode: '400'
