---
- name: Setup networking
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tasks:
    - name: Copy netplan configuration
      become: true
      ansible.builtin.copy:
        src: netplan.yml.j2
        dest: /etc/netplan/02-netcfg.yaml
        # TODO: this needs to apply the netplan after changes

- name: Generate ssh key
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tags:
    - proxy
  tasks:
    - name: Generate key pair
      become: true
      ansible.builtin.shell:
        cmd: ssh-keygen -b 2048 -t rsa -f {{ ansible_env.HOME }}/.ssh/id_rsa -q -N /dev/null
      args:
        creates: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    - name: Retrieve public key
      ansible.builtin.shell:
        cmd: cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub
      changed_when: false
      register: public_key

- name: Setup reverse proxy
  hosts: aws
  become: true
  vars_files:
    - secrets.yml
  tags:
    - proxy
  tasks:
    - name: Add public key
      ansible.posix.authorized_key:
        user: root
        key: "{{ hostvars['server'].public_key.stdout }}"
    - name: Update
      ansible.builtin.package:
        update_cache: true
    - name: Add nginx user
      ansible.builtin.user:
        name: nginx
        shell: /bin/false
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
    - name: Install certbot
      ansible.builtin.package:
        name: certbot
    - name: Install python3-certbot-nginx
      ansible.builtin.package:
        name: python3-certbot-nginx
    - name: Copy nginx configuration
      become: true
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart nginx
    - name: Install certificate
      ansible.builtin.command:
        argv:
          - /usr/bin/certbot
          - --nginx
          - -d
          - home.felixscherz.me
          - -d
          - paperless.felixscherz.me
          - -d
          - grocy.felixscherz.me
          - -d
          - mealie.felixscherz.me
          - -d
          - grafana.felixscherz.me
          - --expand
          - -n
          - --agree-tos
          - --email
          - felixwscherz@gmail.com

  handlers:
    - name: Restart nginx
      become: true
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx

- name: Setup daily sleep cron job
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tasks:
    - name: Add daily sleep cron job for server sleep
      become: true
      ansible.builtin.cron:
        name: "Send server to sleep for 8 hours"
        hour: "22"
        user: root
        job: "sudo rtcwake -m mem -s 28800"
        state: absent


- name: Setup paperless
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tasks:
    - name: Create cronjob for paperless backup
      ansible.builtin.cron:
        name: Paperless backup
        special_time: hourly
        job: docker compose -f ~/paperless/docker-compose.yml exec -T webserver document_exporter ../expor

- name: SSH Hardening and Security
  hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{% if inventory_hostname in groups['home'] %}{{ home.become_password }}{% endif %}"
  tasks:
    - name: Install fail2ban
      ansible.builtin.package:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Create fail2ban jail configuration
      ansible.builtin.template:
        src: fail2ban-jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban

    - name: Backup original SSH config
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        remote_src: yes
        force: no

    - name: Deploy hardened SSH configuration
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify:
        - Restart sshd
        - Restart fail2ban

    - name: Start and enable fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: yes

  handlers:
    - name: Restart fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: restarted

    - name: Restart sshd
      ansible.builtin.systemd:
        # Ubuntu/Debian uses 'ssh' service name, RHEL/CentOS uses 'sshd'
        name: "{{ 'ssh' if inventory_hostname in groups.aws else 'sshd' }}"
        state: restarted


- name: Setup VPN clien
  hosts: home
  tags:
    - vpn
  vars_files:
    - vars.yml
  vars:
    server_pubkey: "{{ proxy.wg_pubkey }}"
    ansible_become_pass: "{{ home.become_password }}"
  become: true
  tasks:
    - name: Install wireguard package
      ansible.builtin.package:
        name: wireguard
        state: present
        update_cache: yes

    - name: Generate private key
      ansible.builtin.shell:
        cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > publickey
        chdir: /etc/wireguard
        creates: /etc/wireguard/publickey

    - name: Get public key
      ansible.builtin.command: cat /etc/wireguard/publickey
      register: publickey_contents
      changed_when: False

    - name: set public key fac
      ansible.builtin.set_fact:
        pubkey: "{{ publickey_contents.stdout }}"

    - name: Create client wireguard config
      ansible.builtin.template:
        dest: /etc/wireguard/wg0.conf
        src: client_wg0.conf.j2
        owner: root
        group: root
        mode: '0600'


- name: Setup VPN server
  hosts: proxy
  tags:
    - vpn
  vars_files:
    - vars.yml
  vars:
    server_privkey: "{{ proxy.wg_privkey }}"
    server_pubkey: "{{ proxy.wg_pubkey }}"
  tasks:
    - name: Install wireguard package
      ansible.builtin.package:
        name: wireguard
        state: present
        update_cache: yes

    - name: Create server wireguard config
      ansible.builtin.template:
        dest: /etc/wireguard/wg0.conf
        src: server_wg0.conf.j2
        owner: root
        group: root
        mode: '0600'
      notify: Restart wireguard

    - name: Enable and persist IP forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: yes
        reload: yes

    - name: Start wireguard and enable on boo
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
  handlers:
    - name: Restart wireguard
      ansible.builtin.systemd_service:
        state: restarted
        name: wg-quick@wg0

- name: Start VPN clien
  hosts: home
  tags:
    - vpn
  vars_files:
    - vars.yml
  vars:
    server_pubkey: "{{ proxy.wg_pubkey }}"
    ansible_become_pass: "{{ home.become_password }}"
  become: true
  tasks:
    - name: Start wireguard and enable on boo
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: yes
        state: restarted

- name: Setup grocy
  hosts: home
  tags:
    - grocy
  vars_files:
    - vars.yml
  vars:
    grocy_home: ~/grocy
  tasks:
    - name: Create application directory
      ansible.builtin.file:
        path: "{{ grocy_home }}"
        state: directory
        mode: '0755'
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ grocy_home }}/config"
        state: directory
    - name: Copy compose file
      ansible.builtin.template:
        src: grocy-docker-compose.yml.j2
        dest: "{{ grocy_home }}/docker-compose.yml"
        mode: '0644'
      notify: Restart docker-compose services
    - name: Start services
      community.docker.docker_compose_v2:
        project_src: ~/grocy
        state: present
  handlers:
    - name: Restart docker-compose services
      community.docker.docker_compose_v2:
        project_src: ~/grocy
        state: restarted


- name: Setup mealie
  hosts: home
  tags:
    - mealie
  vars_files:
    - vars.yml
  vars:
    mealie_home: ~/mealie
  tasks:
    - name: Create application directory
      ansible.builtin.file:
        path: "{{ mealie_home }}"
        state: directory
        mode: '0755'
    - name: Copy compose file
      ansible.builtin.template:
        src: mealie-docker-compose.yml
        dest: "{{ mealie_home }}/docker-compose.yml"
        mode: '0644'
      notify: Restart docker-compose services
    - name: Start services
      community.docker.docker_compose_v2:
        project_src: "{{ mealie_home }}"
        state: present
  handlers:
    - name: Restart docker-compose services
      community.docker.docker_compose_v2:
        project_src: "{{ mealie_home }}"
        state: restarted


- name: Setup OpenCode server
  hosts: home
  tags:
    - opencode
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
    opencode_home: /home/felix/repositories
  become: true
  tasks:
    - name: Create working directory
      ansible.builtin.file:
        path: "{{ opencode_home }}"
        state: directory
        mode: '0755'
        owner: felix
        group: felix

    - name: Create systemd service file
      ansible.builtin.template:
        src: opencode.service.j2
        dest: /etc/systemd/system/opencode.service
        mode: '0644'
      notify:
        - Reload systemd
        - Enable opencode service

    - name: Start opencode service
      ansible.builtin.systemd:
        name: opencode
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable opencode service
      ansible.builtin.systemd:
        name: opencode
        enabled: yes
        state: started


- name: Setup monitoring stack
  hosts: home
  tags:
    - monitoring
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
    monitoring_home: ~/monitoring
  become: true
  tasks:
    - name: Install node exporter on cloud VM
      delegate_to: proxy
      become: true
      block:
        - name: Create node_exporter user
          ansible.builtin.user:
            name: node_exporter
            shell: /bin/false
            home: /
            create_home: false
            system: true

        - name: Download and install node_exporter
          ansible.builtin.unarchive:
            src: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
            dest: /tmp
            remote_src: true
            creates: /tmp/node_exporter-1.6.1.linux-amd64

        - name: Copy node_exporter binary
          ansible.builtin.copy:
            src: /tmp/node_exporter-1.6.1.linux-amd64/node_exporter
            dest: /usr/local/bin/node_exporter
            remote_src: true
            owner: node_exporter
            group: node_exporter
            mode: '0755'

        - name: Create node_exporter systemd service
          ansible.builtin.copy:
            content: |
              [Unit]
              Description=Node Exporter
              Wants=network-online.targe
              After=network-online.targe

              [Service]
              User=node_exporter
              Group=node_exporter
              Type=simple
              ExecStart=/usr/local/bin/node_exporter --collector.systemd

              [Install]
              WantedBy=multi-user.targe
            dest: /etc/systemd/system/node_exporter.service
            mode: '0644'
          notify:
            - Reload systemd
            - Start node_exporter

        - name: Enable and start node_exporter
          ansible.builtin.systemd:
            name: node_exporter
            enabled: true
            state: started
            daemon_reload: true

    - name: Create monitoring directory structure
      become: false
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ monitoring_home }}"
        - "{{ monitoring_home }}/prometheus/config"
        - "{{ monitoring_home }}/grafana/config"
        - "{{ monitoring_home }}/grafana/config/provisioning"
        - "{{ monitoring_home }}/grafana/config/provisioning/datasources"
        - "{{ monitoring_home }}/grafana/config/provisioning/dashboards"
        - "{{ monitoring_home }}/grafana/dashboards"
        - "{{ monitoring_home }}/loki/config"
        - "{{ monitoring_home }}/promtail/config"

    - name: Copy custom exporters
      become: false
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ monitoring_home }}/"
        mode: '0755'
      loop:
        - exporters/

    - name: Copy monitoring configuration files
      become: false
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - src: monitoring-docker-compose.yml.j2
          dest: "{{ monitoring_home }}/docker-compose.yml"
        - src: prometheus-config.yml.j2
          dest: "{{ monitoring_home }}/prometheus/config/prometheus.yml"
        - src: prometheus-alert-rules.yml.j2
          dest: "{{ monitoring_home }}/prometheus/config/alert_rules.yml"
        - src: loki-config.yml.j2
          dest: "{{ monitoring_home }}/loki/config/loki-config.yaml"
        - src: promtail-config.yml.j2
          dest: "{{ monitoring_home }}/promtail/config/promtail-config.yaml"
        - src: grafana.ini.j2
          dest: "{{ monitoring_home }}/grafana/config/grafana.ini"
        - src: grafana-datasources.yml.j2
          dest: "{{ monitoring_home }}/grafana/config/provisioning/datasources/prometheus.yml"
        - src: grafana-dashboards.yml.j2
          dest: "{{ monitoring_home }}/grafana/config/provisioning/dashboards/dashboards.yml"
        - src: grafana-dashboard-overview.json
          dest: "{{ monitoring_home }}/grafana/dashboards/overview.json"
        - src: grafana-dashboard-docker.json
          dest: "{{ monitoring_home }}/grafana/dashboards/docker.json"
      notify: Restart monitoring stack

    - name: Create .env file with secrets
      become: false
      ansible.builtin.template:
        src: monitoring-env.j2
        dest: "{{ monitoring_home }}/.env"
        mode: '0600'
      notify: Restart monitoring stack


    - name: Start monitoring stack
      become: false
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_home }}"
        state: present

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: started

    - name: Restart monitoring stack
      become: false
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_home }}"
        state: restarted

- name: Setup Home Assistant IP Forwarding
  hosts: home
  tags:
    - homeassistant-forward
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  become: true
  tasks:
    - name: Enable IP forwarding on home server
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: yes
        reload: yes

    - name: Install iptables-persistent for rule persistence
      ansible.builtin.package:
        name: iptables-persistent
        state: present
        update_cache: yes

    - name: Create Home Assistant iptables script
      ansible.builtin.template:
        src: homeassistant-iptables.j2
        dest: /usr/local/bin/homeassistant-iptables.sh
        owner: root
        group: root
        mode: '0755'
      notify: Apply Home Assistant iptables rules

    - name: Apply Home Assistant iptables rules
      ansible.builtin.command: /usr/local/bin/homeassistant-iptables.sh
      register: iptables_result
      changed_when: true

    - name: Save iptables rules
      ansible.builtin.shell: |
        iptables-save > /etc/iptables/rules.v4
      notify: Restart networking

    - name: Create systemd service for Home Assistant iptables
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Home Assistant IP Forwarding Rules
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/homeassistant-iptables.sh
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/homeassistant-iptables.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd
        - Enable homeassistant iptables service

  handlers:
    - name: Apply Home Assistant iptables rules
      ansible.builtin.command: /usr/local/bin/homeassistant-iptables.sh

    - name: Restart networking
      ansible.builtin.systemd:
        name: networking
        state: restarted

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable homeassistant iptables service
      ansible.builtin.systemd:
        name: homeassistant-iptables
        enabled: true
        state: started
