- name: Setup reverse proxy
  hosts: aws
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: Update
      ansible.builtin.yum:
        update_cache: true
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
    - name: Install certbot
      ansible.builtin.yum:
        name: certbot
    - name: Install python3-certbot-nginx
      ansible.builtin.yum:
        name: python3-certbot-nginx

- name: Setup tunneling via ssh
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tasks:
    - name: Copy key file
      ansible.builtin.copy:
        src: ./files/ec2.pem
        dest: ./.ssh/ec2.pem
        mode: '400'
    - name: Copy reverse tunnel service
      become: true
      ansible.builtin.copy:
        src: ./files/reverse-tunnel.service
        dest: /etc/systemd/system/reverse-tunnel.service
        mode: '400'
      notify:
        - Restart reverse tunnel
    - name: Create cronjob for paperless backup
      ansible.builtin.cron:
        name: Paperless backup
        special_time: hourly
        job: docker compose -f ~/paperless/docker-compose.yml exec -T webserver document_exporter ../export

  handlers:
    - name: Restart reverse tunnel
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true
        state: restarted
        name: reverse-tunnel.service

- name: Setup paperless
  hosts: home
  vars_files:
    - vars.yml
  vars:
    ansible_become_pass: "{{ home.become_password }}"
  tasks:
    - name: Create cronjob for paperless backup
      ansible.builtin.cron:
        name: Paperless backup
        special_time: hourly
        job: docker compose -f ~/paperless/docker-compose.yml exec -T webserver document_exporter ../export
